### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by theo-armour**
Add link to working demo

### CODE REVIEW

**Comment by cferdinandi** [comment]
Thanks for this, Theo, but there's really nothing to "demo" in this case. This is the boilerplate to get you started, but there's no library to show in this code.

**Comment by theo-armour** [comment]
Whenever you have something that can happen when you clink on a link, include the link!

No matter how basic, how minimal, how primitive, seeing something run for the first is a thrill when you are a new user,

**Comment by cferdinandi** [comment]
For sure, but there's nothing happen yet in this file (other than logging the starting functions). Given that it all happens in the console, I personally think a demo is more confusing than helpful.

**Comment by theo-armour** [comment]
When the page opened, it was clear to me what to do.

When I open ed console, I saw the results

And I was happy.

image

Perhaps a better title for the link might give a better indication, For example "Run the code in your browser now!"

**Comment by cferdinandi** [comment]
This is designed to be "follow along with the video" code, not a self-contained bit of code.

**Comment by theo-armour** [comment]
@cferdinandi 

I have no dispute with any of your points. They are all reasonable.

Nonetheless it's always nice to have even more. So one of the wonderful things about JavaScript is that it runs in your browser. Click the button and go. Nothing to install. Nothing to download. Click save. Refresh the page and, Presto!, it runs.

I like to remind people - beginners or experts - about this delight as often as possible. Adding a link that runs the script is a fun reminder of this ability.

Wait there's more

Once you have a number of scripts, it can become difficult to remember which script does what. Often a quick glimpse of the opening screen is enough for you to say to yourself. "Nope, not that one, Try the next". This is a lot easier when you can just click links tin the read me files.

Anyway, don't let me slow down your coding. Keep leading us forward!

**Pull request closed without merging**
